server:
  port: 8081
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/orders"
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456Aa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: order-service